update sonar

diff --git a/.github/workflows/SonarCloud.yml b/.github/workflows/SonarCloud.yml
--- a/.github/workflows/SonarCloud.yml
+++ b/.github/workflows/SonarCloud.yml
@@ -17,45 +17,25 @@ jobs:
         run: |
           sudo apt-get -q update
           sudo add-apt-repository -y ppa:deadsnakes/ppa
-          sudo apt remove -y libunwind-14-dev
-          sudo apt-get install g++-13
-          sudo apt-get install linux-libc-dev
-          sudo apt-get install git
-          sudo apt-get install build-essential
-          sudo apt-get install automake
-          sudo apt-get install libtool
-          sudo apt-get install python3.12-dev
-          sudo apt-get install zlib1g-dev
-          sudo apt-get install gettext
-          sudo apt-get install swig
-          sudo apt-get install libgstreamer1.0-dev
-          sudo apt-get install libgstreamer-plugins-base1.0-dev
-          sudo apt-get install libfreetype6-dev
-          sudo apt-get install libsigc++-2.0-dev
-          sudo apt-get install libfribidi-dev
-          sudo apt-get install libavahi-client-dev
-          sudo apt-get install libjpeg-turbo8-dev
-          sudo apt-get install libgif-dev
-          sudo apt-get install libcurl4-openssl-dev
+          sudo apt-get install -y g++-13 linux-libc-dev git build-essential automake libtool python3.12-dev zlib1g-dev gettext swig libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libfreetype6-dev libsigc++-2.0-dev libfribidi-dev libavahi-client-dev libjpeg-turbo8-dev libgif-dev libcurl4-openssl-dev
 
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+          fetch-depth: 0  # Disabilita il clone superficiale per una migliore analisi
 
       - name: Install sonar-scanner and build-wrapper
         uses: SonarSource/sonarcloud-github-c-cpp@v2
 
       - uses: actions/setup-python@v5
         with:
-          python-version: '3.13'
-          
-      - name: Build osno dependencies
+          python-version: '3.12'
+
+      - name: Build enigma2 dependencies
         env:
           CC: "gcc-13"
           CXX: "g++-13"
         run: |
-          echo "installing libdvbsi++"
-          pushd .
+          echo "Installazione di libdvbsi++"
           cd /tmp
           git clone --depth 1 https://github.com/oe-alliance/libdvbsi.git
           cd libdvbsi
@@ -63,9 +43,7 @@ jobs:
           ./configure
           make
           sudo make install
-          popd
-          echo "installing tuxbox"
-          pushd .
+          echo "Installazione di tuxbox"
           cd /tmp
           git clone --depth 1 https://github.com/oe-alliance/tuxtxt.git
           cd tuxtxt/libtuxtxt
@@ -78,15 +56,16 @@ jobs:
           ./configure --with-boxtype=generic DVB_API_VERSION=5
           make
           sudo make install
-          popd
 
-      - name: Install sonar-scanner and build-wrapper
-        uses: SonarSource/sonarcloud-github-c-cpp@v2
       - name: Run build-wrapper
         env:
           CC: "gcc-13"
           CXX: "g++-13"
         run: |
+          if [ ! -f ./Makefile ]; then
+            echo "Errore: Makefile non trovato nella directory corrente."
+            exit 1
+          fi
           sed -i 's/include lib main data po tools/include lib main tools/g' Makefile.am
           autoreconf -i
           ./configure --with-libsdl=no --with-boxtype=nobox --enable-dependency-tracking ac_cv_prog_c_openmp=-fopenmp --with-gstversion=1.0 --with-textlcd
@@ -97,4 +76,5 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          sonar-scanner --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
+          sonar-scanner -Dsonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
+
